### ISSUE TITLE
Friendlier Implementation w/o Termux

### ISSUE THREAD

**Issue by LPX55** [s4l1h/androidproxy#1]
First off, I wanted to thank you for your work! Your repo helped me a lot in understanding how a device can be turned into a mobile proxy.

Probably a very stupid question, but I know very little about networking and android dev. A client of mine wanted to see if it was possible to do web scraping on the cloud through his Android device's unlimited data plan. 

I managed to use your repo to have everything authenticated and communicating beautifully, and now my client can happily spend his unlimited data on scraping activities through his "mobile IP address" -- I put the quotes there because I have no idea if the platforms being scraped are aware that it's only a proxy IP. 

There must be a more easier, scalable way to get this accomplished, right? A simple APK-file installation with an app that has a big red button that says "PROXY ON" would be ideal (half-joking, but you know how clients can be..... slow to learn or easy to break things).

Any pointers in the right direction would be super appreciated. Not even sure where to begin without Termux. Am I overthinking this way too hard?

**Comment by s4l1h** [comment]
@hanyoonLDA  
You can do that in many ways. You just need to find a way to overcome to NAT.( most popular way is UDP hole punching)
Best easy way to do that create a virtual private network.

https://tailscale.com 
https://play.google.com/store/apps/details?id=org.proxydroid

When you install tailscale+proxydroid to your client devices. All clients will have a private ip address.
After than client devices will be able to communicate with each other.

Device 1 ( Raspberry pi )  private ip. 100.0.0.1 ( maybe squid proxy? )
Device 2 ( Android )  private ip. 100.0.0.5 ( proxy droid works on port 1080 ) 
Device 3 ( IOS )  private ip. 100.0.0.8
Device 4 ( linux server )  private ip. 100.0.0.9 - public ip 11.11.12.13

In a case you want to share your android proxy via device 4. you just need to use a port forwarding software.

https://www.cyberciti.biz/faq/linux-unix-tcp-port-forwarding/
Forward any incoming request 11.11.12.13:5000 to 100.0.0.5:1080 in device 4.
socat TCP-LISTEN:5000,fork TCP:100.0.0.5:1080

also you can achieve that via IPTABLES + MASQUERADE or tcp proxy(haproxy maybe?)

If you don't have any public IP address for sharing you can use ngrok or https://github.com/cloudflare/cloudflared

**Comment by LPX55** [comment]
Appreciate the response! Going to be honest, 50% of what you wrote just went wooosh over my head. 😅 I've never had any formal networking training, so all this is pretty foreign to me. 

edit: Read it a couple more times. I misunderstood the Devices #1-#4 as a network configuration and was totally confused. But from what I am now understanding is that the linux server is the forwarding port for device 1 OR device 2 OR device 3, correct? You were just giving me a list of potential devices that could connect to forwarding server (device 4).

I'm a little confused to where the SSHD client/port comes into play. If our end users do not need access to SSH, theoretically it can just be taken out of the equation, right? Or am I missing something.

I'll do a bit more digging into this, but again, super appreciate your response!

**Comment by s4l1h** [comment]
You just need to put your clients same network. You can do that via https://tailscale.com/ as I mentioned before.
Someone need to manage the port forwarding on the linux server which is a gate to the internet.

You can follow some think like that pattern for manage to port.
socat TCP-LISTEN:5001,fork TCP:100.0.0.1:1080
socat TCP-LISTEN:5002,fork TCP:100.0.0.2:1080
socat TCP-LISTEN:5003,fork TCP:100.0.0.3:1080
socat TCP-LISTEN:5004,fork TCP:100.0.0.4:1080

Or a piece of  Golang code can handle that.( golang tcp proxy, golang listening multiple ports)
